#!/bin/bash

. __subpro_variables


all_sublime_project_files()
{
    find ${PROJECT_DIR} -name "*.${PROJECT_SUFFIX}" | while read name
    do
        if [[ "$name" =~ ."${PROJECT_SUFFIX}"$ ]]; then
            echo $name | awk '{n=split($0,a,"/"); print a[n]}' | sed -e "s/.${PROJECT_SUFFIX}//"
        fi
    done
}


_subpro()
{
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    if [ $COMP_CWORD -lt 3 ]; then
        COMPREPLY=($(compgen -W "`all_sublime_project_files`" -- ${cur}))
    else
        COMPREPLY=($(compgen -f ${cur}))
    fi
}


complete -F _subpro subpro
