#!/bin/bash

PROJECT_DIR=~/.subpro/
BASE_CONFIG_DIR=${PROJECT_DIR}base/
SUBLIME_CMD="Sublime Text"

_open_sublime_project()
{
    if [ -n "$1" ]; then
        open -a $SUBLIME_CMD "$1"
        return 0
    fi

    return 1
}

open_sublime_project()
{
    find "$PROJECT_DIR" -name "$1.sublime-project" | while read name
    do
        _open_sublime_project "$name"

        if [ $? -eq 0 ]; then
            exit 0
        fi
    done
}

delete_sublime_project()
{
    for suffix in sublime-project sublime-workspace
    do
        txt=${1}.${suffix}
        find "$PROJECT_DIR" -name "*${suffix}" | while read name
        do
            m=`echo $name | grep /$txt`

            if [ -n "$m" ]; then
                rm "$name"
                echo "delete $name"
            fi
        done
    done
}

create_sublime_project()
{
    group=$1
    if [ -n "$4" ]; then
        dest_project=$4
    else
        dest_project=$3
    fi

    target="\"path\": \"`pwd`/${2}\","
    escape=`echo $target | sed "s/\//\\\\\\\\\//g"`
    dest="${PROJECT_DIR}${group}/${dest_project}.sublime-project"

    mkdir -p "${PROJECT_DIR}${group}"

    if [ -a "${BASE_CONFIG_DIR}${group}.sublime-project" ]; then
        cp "${BASE_CONFIG_DIR}${group}.sublime-project" "$dest"
    else
        cp "${BASE_CONFIG_DIR}base.sublime-project" "$dest"
    fi

    sed -i '' -e "s/\"path\":.*/${escape}/" "$dest"
    open -a $SUBLIME_CMD "$dest"
}


show_usage()
{
    echo "Example usage:"
    echo "  subpro [project]"
    echo "  subpro create|c [package] [project path] [name]"
    echo "  subpro delete|del|d [project]"
}

case $# in
    0) show_usage ;;
    1) open_sublime_project $1 ;;
    2) case "$1" in
            d | del | delete)
                delete_sublime_project $2 ;;
       esac
       ;;
    *) case "$1" in
           c | create)
                create_sublime_project $2 $3 $4 $5;;
       esac
       ;;
esac
