#!/bin/bash

PROJECT_DIR=~/.subpro/
PROJECT_SUFFIX=sublime-project


all_sublime_project_files()
{
    find "${PROJECT_DIR}" -type f -name "*.${PROJECT_SUFFIX}" | xargs -I{} basename "{}" ".${PROJECT_SUFFIX}"
}


_subpro()
{
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    if [ $COMP_CWORD -lt 3 ]; then
        COMPREPLY=($(compgen -W "`all_sublime_project_files`" -- ${cur}))
    else
        COMPREPLY=($(compgen -f ${cur}))
    fi
}


complete -F _subpro subpro
