#!/bin/bash

PROJECT_DIR=~/.subpro/
BASE_CONFIG_DIR=${PROJECT_DIR}base/
SUBLIME_CMD="Sublime Text"
PROJECT_SUFFIX=sublime-project


all_sublime_project_files()
{
    find "${PROJECT_DIR}" -name "*.${PROJECT_SUFFIX}" | while read path
    do
        basename "$path" | sed -e "s/.${PROJECT_SUFFIX}//"
    done
}


_subpro()
{
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    if [ $COMP_CWORD -lt 3 ]; then
        COMPREPLY=($(compgen -W "`all_sublime_project_files`" -- ${cur}))
    else
        COMPREPLY=($(compgen -f ${cur}))
    fi
}


complete -F _subpro subpro
