#!/bin/sh

ProjectDir=~/.subpro/
SettingBase=${ProjectDir}base/

_open_sublime_project()
{
    if [ -n "$1" ]; then
        open -a 'Sublime Text' "$1"
        return 0
    fi

    return 1
}

open_sublime_project()
{
    find "$ProjectDir" -name "$1.sublime-project" | while read name
    do
        _open_sublime_project "$name"

        if [ $? -eq 0 ]; then
            exit 0
        fi
    done
}

delete_sublime_project()
{
    for prefix in sublime-project sublime-workspace
    do
        find "$ProjectDir" -name "*${prefix}" | while read name
        do
            txt=${1}.${prefix}
            m=`echo $name | grep /$txt`

            if [ -n "$m" ]; then
                rm -r "$name"
                return 0
            fi
        done
    done
}

create_sublime_project()
{
    folder=$1

    if [ -n "$3" ]; then
        project=$3
    else
        project=$2
    fi

    target="\"path\": \"`pwd`/${2}\","
    escape=`echo $target | sed "s/\//\\\\\\\\\//g"`
    dest="${ProjectDir}${folder}/${project}.sublime-project"

    mkdir -p "${ProjectDir}${folder}"

    if [ -a "${SettingBase}${folder}.sublime-project" ]; then
        cp "${SettingBase}${folder}.sublime-project" "$dest"
    else
        cp "${SettingBase}base.sublime-project" "$dest"
    fi

    sed -i '' -e "s/\"path\":.*/${escape}/" "$dest"
    open -a 'Sublime Text' "$dest"
}


case $# in
    1) open_sublime_project $1 ;;
    2) case "$1" in
            d | del | delete)
                delete_sublime_project $2 ;;
       esac
       ;;
    *) case "$1" in
           c | create)
                create_sublime_project $2 $3 $4;;
       esac
       ;;
esac
