#!/bin/bash

PROJECT_DIR=~/.subpro/
BASE_CONFIG_DIR=${PROJECT_DIR}base
PROJECT_SUFFIX=sublime-project
APPLICATION_DIR="Applications"
if [ -d "/${APPLICATION_DIR}/Sublime Text.app" -o -d "${HOME}/${APPLICATION_DIR}/Sublime Text.app" ]; then
    SUBLIME_CMD="Sublime Text"
else
    SUBLIME_CMD="Sublime Text 2"
fi


open_sublime_project()
{
    find "${PROJECT_DIR}" -type f -name "$1.${PROJECT_SUFFIX}" -exec open -a "${SUBLIME_CMD}" "{}" \;
}

delete_sublime_project()
{
    for suffix in "${PROJECT_SUFFIX}" sublime-workspace
    do
        filename=${1}.${suffix}
        find "${PROJECT_DIR}" -name "*.${suffix}" | while read path
        do
            if [[ $path =~ /"${filename}"$  ]]; then
                echo "delete ${path}"
                rm "${path}"
                break
            fi
        done
    done
}

create_sublime_project()
{
    group=$1
    dest_project=$3 && [ -z "$dest_project" ] && dest_project=$2

    destPath="${PROJECT_DIR}${group}/${dest_project}.${PROJECT_SUFFIX}"

    # copy project config file
    mkdir -p "${PROJECT_DIR}${group}"
    if [ -f "${BASE_CONFIG_DIR}/${group}.${PROJECT_SUFFIX}" ]; then
        cp "${BASE_CONFIG_DIR}/${group}.${PROJECT_SUFFIX}" "${destPath}"
    else
        cp "${BASE_CONFIG_DIR}/base.${PROJECT_SUFFIX}" "${destPath}"
    fi

    # replace path to project path.
    target="\"path\": \"`pwd`/${2}\","
    escape=`echo $target | sed "s/\//\\\\\\\\\//g"`
    sed -i '' -e "s/\"path\":.*/${escape}/" "${destPath}"

    open -a "${SUBLIME_CMD}" "${destPath}"
}

show_usage()
{
    echo "Example usage:"
    echo "  subpro [project]"
    echo "  subpro create|c [package] [project path] [name]"
    echo "  subpro delete|del|d [project]"
}


case $# in
    0) show_usage ;;
    1) open_sublime_project $1 ;;
    2) case "$1" in
            d | del | delete)
                delete_sublime_project $2 ;;
       esac
       ;;
    *) case "$1" in
           c | create)
                create_sublime_project $2 $3 $4 $5 ;;
       esac
       ;;
esac
